FROM python:3.10

WORKDIR /app

COPY ./requirements.txt /app/

RUN pip3 install --no-cache-dir -r requirements.txt

RUN adduser --uid 1000 --disabled-password --system app

USER app

COPY ./manage.py ./manage.sh ./run.py /app/

COPY ./app /app/app/

ENV DATABASE_URI sqlite://

ENV FLASK_ENV development

CMD ["python3", "run.py"]
